# Generated by Django 4.0.4 on 2022-05-31 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_help'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='help',
            name='image',
        ),
        migrations.CreateModel(
            name='HelpMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='help/')),
                ('questions', models.ManyToManyField(to='news.help')),
            ],
        ),
    ]
