# Generated by Django 4.0.4 on 2022-06-01 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_remove_help_image_helpmain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helpmain',
            name='questions',
        ),
        migrations.AddField(
            model_name='helpmain',
            name='questions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.help'),
        ),
    ]
