# Generated by Django 4.0.4 on 2022-06-01 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_help_img_delete_helpmain_help_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='help_img',
            options={'verbose_name': 'Фотография для помощи', 'verbose_name_plural': 'Фотография для помощи'},
        ),
    ]
