# Generated by Django 4.0.4 on 2022-06-02 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_alter_help_img_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Help',
        ),
        migrations.DeleteModel(
            name='Help_img',
        ),
    ]
