# Generated by Django 4.0.4 on 2022-06-21 10:27

import ckeditor.fields
import colorful.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import product.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='collection/', verbose_name='Фотография')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Коллекция',
                'verbose_name_plural': 'Коллекции',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('vendor_code', models.CharField(max_length=255, verbose_name='Артикул')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('discount', models.IntegerField(blank=True, default=0, null=True, verbose_name='Скидка')),
                ('new_price', models.FloatField(blank=True, default=0, null=True, verbose_name='Цена после скидки')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание')),
                ('size_range', models.CharField(help_text='Пример: 42-50', max_length=5, validators=[product.models.size_validate], verbose_name='Размерный ряд')),
                ('fabric_structure', models.CharField(max_length=255, verbose_name='Состав ткани')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество')),
                ('material', models.CharField(max_length=255, verbose_name='Материал')),
                ('bestseller', models.BooleanField(default=False, verbose_name='Хит продаж')),
                ('new', models.BooleanField(default=True, verbose_name='Новый')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.collection', verbose_name='Коллекция')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='Image_color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product/', verbose_name='Фотография')),
                ('color', colorful.fields.RGBColorField(default='#fff', verbose_name='Цвет')),
                ('image_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_products', to='product.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
