# Generated by Django 4.0.4 on 2022-06-01 09:59

import ckeditor.fields
import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('vendor_code', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('description', ckeditor.fields.RichTextField()),
                ('size_range', models.CharField(max_length=20)),
                ('fabric_structure', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('material', models.CharField(max_length=255)),
                ('bestseller', models.BooleanField(default=False)),
                ('new', models.BooleanField(default=False)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.collection')),
            ],
        ),
        migrations.CreateModel(
            name='Image_color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product/')),
                ('color', colorfield.fields.ColorField(default='#fff', image_field=None, max_length=18, samples=None)),
                ('image_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.product')),
            ],
        ),
    ]
