# Generated by Django 4.0.4 on 2022-06-01 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_image_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='new_price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.IntegerField(null=True),
        ),
    ]
