# Generated by Django 4.0.4 on 2022-06-18 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_favorite_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size_range',
            field=models.CharField(help_text='Пример: 42-50', max_length=20, verbose_name='Размерный ряд'),
        ),
    ]
