# Generated by Django 4.0.4 on 2022-06-01 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_new_price_alter_product_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='new_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
