# Generated by Django 4.0.4 on 2022-06-01 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_discount_alter_product_new_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='favorite',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
    ]
