# Generated by Django 4.0.4 on 2022-06-01 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_favorite_alter_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='new',
            field=models.BooleanField(default=True),
        ),
    ]
