# Generated by Django 4.0.4 on 2022-06-16 16:53

import ckeditor.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import main.validate


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('text', ckeditor.fields.RichTextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'О нас',
                'verbose_name_plural': 'О нас',
            },
        ),
        migrations.CreateModel(
            name='Advantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст')),
                ('img', models.ImageField(upload_to='advantage/', validators=[main.validate.validate_SVG_PNG], verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'Наше преимущество',
                'verbose_name_plural': 'Наши преимущества',
            },
        ),
        migrations.CreateModel(
            name='Call_back',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('phone_number', models.CharField(blank=True, default='+996(700)12-34-56', max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+996(700)12-34-56'.", regex='(\\+996)\\(\\d{3}\\)\\d{2}-\\d{2}-\\d{2}')], verbose_name='Номер телефона')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('type', models.CharField(max_length=255, verbose_name='Тип звонка')),
                ('status', models.CharField(choices=[('1', 'Нет'), ('2', 'Да')], default=1, max_length=5, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Обратный звонок',
                'verbose_name_plural': 'Обратные звонки',
            },
        ),
        migrations.CreateModel(
            name='Footer_first_side',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='', validators=[main.validate.validate_SVG_PNG], verbose_name='Логотип')),
                ('info', models.TextField(verbose_name='Тестовая информация')),
                ('number', models.IntegerField(verbose_name='Номер в хедере')),
            ],
            options={
                'verbose_name': 'Footer',
                'verbose_name_plural': 'Footer',
            },
        ),
        migrations.CreateModel(
            name='Help_img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='help/', verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'Фотография для помощи',
                'verbose_name_plural': 'Фотография для помощи',
            },
        ),
        migrations.CreateModel(
            name='PublicOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('text', ckeditor.fields.RichTextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Публичная оферта',
                'verbose_name_plural': 'Публичная оферта',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(null=True, verbose_name='Ссылка')),
                ('image', models.ImageField(null=True, upload_to='slider/', verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'Слайдер',
                'verbose_name_plural': 'Слайдер',
            },
        ),
        migrations.CreateModel(
            name='Help',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='main.help_img', verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'Помощь',
                'verbose_name_plural': 'Помощь',
            },
        ),
        migrations.CreateModel(
            name='Footer_second_side',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social', models.CharField(choices=[('phone', 'phone'), ('email', 'email'), ('instagram', 'instagram'), ('telegram', 'telegram'), ('whatsapp', 'whatsapp')], max_length=255, verbose_name='Контакты')),
                ('link', models.TextField(verbose_name='Ссылка')),
                ('footer', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='link', to='main.footer_first_side')),
            ],
        ),
        migrations.CreateModel(
            name='AboutUsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about_us/')),
                ('is_active', models.BooleanField(default=False)),
                ('is_main', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('aboutus', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='about_img', to='main.aboutus')),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Фотографии',
            },
        ),
    ]
