# Generated by Django 4.0.4 on 2022-06-20 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_call_back_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutusimage',
            name='is_active',
        ),
    ]
