# Generated by Django 4.0.4 on 2022-06-18 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_help_img_options_alter_call_back_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footer_first_side',
            options={'verbose_name': 'Футер', 'verbose_name_plural': 'Футер'},
        ),
    ]
