# Generated by Django 4.0.4 on 2022-06-01 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_publicoffer_options_publicoffer_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(null=True)),
            ],
            options={
                'verbose_name': 'Слайдер',
            },
        ),
        migrations.CreateModel(
            name='Slider_img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slider/')),
                ('slider', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slider_img', to='main.slider')),
            ],
            options={
                'verbose_name': 'Фотография для слайдера',
                'verbose_name_plural': 'Фотографии для слайдера',
            },
        ),
    ]
