# Generated by Django 4.0.4 on 2022-06-01 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_slider_slider_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='image',
            field=models.ImageField(null=True, upload_to='slider/'),
        ),
        migrations.DeleteModel(
            name='Slider_img',
        ),
    ]
