# Generated by Django 4.0.4 on 2022-06-01 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_slider_image_delete_slider_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name': 'Слайдер', 'verbose_name_plural': 'Слайдер'},
        ),
    ]
