# Generated by Django 4.0.4 on 2022-06-04 18:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_help_img_help'),
    ]

    operations = [
        migrations.CreateModel(
            name='Call_back',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+996700000000'. Up to 15 digits allowed.", regex='^((+996)[\\- ]?)?(\\(?\\d{3}\\)?[\\- ]?)?[\\d\\- ]{7,10}$')])),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('1', 'Нет'), ('2', 'Да')], default=1, max_length=5)),
            ],
            options={
                'verbose_name': 'Обратный звонок',
                'verbose_name_plural': 'Обратные звонки',
            },
        ),
    ]
