# Generated by Django 4.0.4 on 2022-06-06 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_call_back_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer_first_side',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='')),
                ('info', models.TextField()),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Footer_second_side',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social', models.CharField(choices=[('1', 'phone'), ('2', 'email'), ('3', 'instagram'), ('4', 'telegram'), ('5', 'whatsapp')], max_length=255)),
                ('link', models.TextField()),
            ],
            options={
                'verbose_name': 'Footer second side',
                'verbose_name_plural': 'Footer second side',
            },
        ),
    ]
