# Generated by Django 4.0.4 on 2022-06-06 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_footer_first_side_footer_second_side'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footer_second_side',
            options={},
        ),
        migrations.AddField(
            model_name='footer_second_side',
            name='footer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.footer_first_side'),
        ),
    ]
