# Generated by Django 4.0.4 on 2022-06-06 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_footer_second_side_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer_second_side',
            name='footer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.footer_first_side'),
        ),
    ]
