# Generated by Django 4.0.4 on 2022-06-06 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_footer_second_side_footer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footer_first_side',
            options={'verbose_name': 'Footer', 'verbose_name_plural': 'Footer'},
        ),
    ]
