# Generated by Django 4.0.4 on 2022-06-06 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_footer_first_side_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer_second_side',
            name='footer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='link', to='main.footer_first_side'),
        ),
    ]
