# Generated by Django 4.0.4 on 2022-06-06 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_footer_second_side_footer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer_second_side',
            name='social',
            field=models.CharField(choices=[('phone', 'phone'), ('email', 'email'), ('instagram', 'instagram'), ('telegram', 'telegram'), ('whatsapp', 'whatsapp')], max_length=255),
        ),
    ]
