# Generated by Django 4.0.4 on 2022-06-20 09:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(blank=True, default='+996(700)12-34-56', max_length=17, validators=[django.core.validators.RegexValidator(message="Format: '+996(700)12-34-56'.", regex='(\\+996)\\(\\d{3}\\)\\d{2}-\\d{2}-\\d{2}')], verbose_name='Номер телефона'),
        ),
    ]
