# Generated by Django 4.0.4 on 2022-06-14 11:28

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_orders_options_alter_order_check_client_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order_check',
            options={'verbose_name': 'Чек', 'verbose_name_plural': 'Чек'},
        ),
        migrations.AlterModelOptions(
            name='product_to_order',
            options={'verbose_name': 'Продукты', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterField(
            model_name='orders',
            name='country',
            field=django_countries.fields.CountryField(max_length=30, null=True, verbose_name='Страна'),
        ),
    ]
