# Generated by Django 4.0.4 on 2022-06-20 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_client_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата оформления'),
        ),
    ]
