# Generated by Django 4.0.4 on 2022-06-14 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_order_check_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='country',
            field=models.CharField(max_length=30, null=True, verbose_name='Страна'),
        ),
    ]
