# Generated by Django 4.0.4 on 2022-06-20 09:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_alter_client_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now, null=True, verbose_name='Дата оформления'),
        ),
    ]
