# Generated by Django 4.0.4 on 2022-06-20 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_alter_client_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_check',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_check', to='cart.client'),
        ),
        migrations.AlterField(
            model_name='product_to_order',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='cart.order_check'),
        ),
    ]
