# Generated by Django 4.0.4 on 2022-06-18 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_delete_usermanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(max_length=255, null=True, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(max_length=30, null=True, verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='user',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата оформления'),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=30, null=True, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=30, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, default='+996(700)12-34-56', max_length=17, verbose_name='Номер телефона'),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('done', 'Оформлен'), ('denyed', 'Отменен')], default='new', max_length=30, verbose_name='Статус заказа'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Электронная почта'),
        ),
    ]
